name: shell commands
on: [push]
jobs:
    run-shell-command:
      runs-on: ubuntu-latest
      steps:
        - name: echo a string
          run: echo "test"
        - name: multiline script
          run: |
              node -v
              npm -v
        - name: check current directory
          run: pwd
        - name: SonarQube Quality Gate Check
          uses: SonarSource/sonarqube-quality-gate-action@v1.0.0
