name: shell commands
on: [issues]
jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:10.18-jessie

    steps:
    - uses: actions/checkout@v2

    - name: Display structure of downloaded files
      run: ls -R