name: shell commands
on: [push]
jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:10.18-jessie

    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v3
      with:
        name: my-artifact
      
    - name: Display structure of downloaded files
      run: ls -R